// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8TaFD_YEZZ3FaV1hXgCxFn_daUfGdDdQ',
    appId: '1:26248641577:web:a46302c0414bf339793038',
    messagingSenderId: '26248641577',
    projectId: 'tasks-ddbe0',
    authDomain: 'tasks-ddbe0.firebaseapp.com',
    storageBucket: 'tasks-ddbe0.appspot.com',
    measurementId: 'G-QQT0PK47TW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMdxva_6cmH-BEhQBh2p50TwtC8LtoO8Y',
    appId: '1:26248641577:android:49ddd2bc08b50385793038',
    messagingSenderId: '26248641577',
    projectId: 'tasks-ddbe0',
    storageBucket: 'tasks-ddbe0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5lxgIny-6d3RdsZQv-vWmjkdx9Dmmyw8',
    appId: '1:26248641577:ios:9396eefe9728641d793038',
    messagingSenderId: '26248641577',
    projectId: 'tasks-ddbe0',
    storageBucket: 'tasks-ddbe0.appspot.com',
    iosBundleId: 'com.flutter.todoApp',
  );
}
